<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shweta-PC" failures="7" tests="54" name="dsAlgo_TestClasses.LinkedList_TestClass" time="378.062" errors="1" timestamp="2025-03-13T18:05:09 EDT" skipped="16">
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="validLoginDataBase" time="4.823"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="callValidLogInData" time="5.277"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="introductionNavigation" time="5.564"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="introductionTryHere" time="7.333"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="introductionTryHere" time="7.243"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="introductionTryHere" time="7.093"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeIntroductionTryHere" time="6.054">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:111)
at dsAlgo_TestClasses.LinkedList_TestClass.clickRunWithNoCodeIntroductionTryHere(LinkedList_TestClass.java:75)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickRunWithNoCodeIntroductionTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeIntroductionTryHere" time="6.363">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeIntroductionTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeIntroductionTryHere" time="6.728">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeIntroductionTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="creatingLinkedListNavigation" time="5.890"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="creatingLinkedListTryHere" time="7.107"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="creatingLinkedListTryHere" time="7.127"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="creatingLinkedListTryHere" time="7.206"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeCreatingLinkedListTryHere" time="6.689">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeCreatingLinkedListTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeCreatingLinkedListTryHere" time="7.868">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeCreatingLinkedListTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeCreatingLinkedListTryHere" time="6.407">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:111)
at dsAlgo_TestClasses.LinkedList_TestClass.clickRunWithNoCodeCreatingLinkedListTryHere(LinkedList_TestClass.java:105)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickRunWithNoCodeCreatingLinkedListTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="typesOfLinkedListNavigation" time="6.585"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="typesOfLinkedListTryHere" time="7.095"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="typesOfLinkedListTryHere" time="7.157"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="typesOfLinkedListTryHere" time="7.449"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeTypesOfLinkedListTryHere" time="6.924">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeTypesOfLinkedListTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeTypesOfLinkedListTryHere" time="6.707">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:111)
at dsAlgo_TestClasses.LinkedList_TestClass.clickRunWithNoCodeTypesOfLinkedListTryHere(LinkedList_TestClass.java:135)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickRunWithNoCodeTypesOfLinkedListTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeTypesOfLinkedListTryHere" time="7.090">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeTypesOfLinkedListTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="implementLinkedListNavigation" time="5.482"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="implementLinkedListTryHere" time="6.898"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="implementLinkedListTryHere" time="6.929"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="implementLinkedListTryHere" time="6.821"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeImplementLinkedListTryHere" time="6.275">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeImplementLinkedListTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeImplementLinkedListTryHere" time="6.305">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeImplementLinkedListTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeImplementLinkedListTryHere" time="6.494">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:111)
at dsAlgo_TestClasses.LinkedList_TestClass.clickRunWithNoCodeImplementLinkedListTryHere(LinkedList_TestClass.java:165)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickRunWithNoCodeImplementLinkedListTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="traversalNavigation" time="5.462"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="traversalTryHere" time="7.001"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="traversalTryHere" time="7.109"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="traversalTryHere" time="7.177"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeTraversalTryHere" time="6.663">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeTraversalTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeTraversalTryHere" time="6.661">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:111)
at dsAlgo_TestClasses.LinkedList_TestClass.clickRunWithNoCodeTraversalTryHere(LinkedList_TestClass.java:195)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickRunWithNoCodeTraversalTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeTraversalTryHere" time="6.356">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeTraversalTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="insertionNavigation" time="5.344"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="insertionTryHere" time="6.847"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="insertionTryHere" time="6.930"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="insertionTryHere" time="7.699"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeInsertionTryHere" time="6.767">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeInsertionTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeInsertionTryHere" time="6.075">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:111)
at dsAlgo_TestClasses.LinkedList_TestClass.clickRunWithNoCodeInsertionTryHere(LinkedList_TestClass.java:225)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickRunWithNoCodeInsertionTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeInsertionTryHere" time="6.933">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeInsertionTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="deletionNavigation" time="5.483"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="deletionTryHere" time="7.027"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="deletionTryHere" time="6.938"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="deletionTryHere" time="7.207"/>
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeDeletionTryHere" time="6.716">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:111)
at dsAlgo_TestClasses.LinkedList_TestClass.clickRunWithNoCodeDeletionTryHere(LinkedList_TestClass.java:255)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickRunWithNoCodeDeletionTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeDeletionTryHere" time="6.850">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeDeletionTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="clickRunWithNoCodeDeletionTryHere" time="6.868">
    <skipped/>
  </testcase> <!-- clickRunWithNoCodeDeletionTryHere -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="practiceQuestionsNavigation" time="13.075">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;link text&quot;,&quot;selector&quot;:&quot;Practice Questions&quot;}
  (Session info: chrome=131.0.6778.204)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &#039;4.29.0&#039;, revision: &#039;5fc1ec94cb&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;23.0.1&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [e6ec512e6488a6d209722b867475bc9a, findElement {value=Practice Questions, using=link text}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.204, chrome: {chromedriverVersion: 131.0.6778.264 (2d05e315153..., userDataDir: C:\Users\mahaj\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:58697}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:58697/devtoo..., se:cdpVersion: 131.0.6778.204, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: e6ec512e6488a6d209722b867475bc9a" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"link text","selector":"Practice Questions"}
  (Session info: chrome=131.0.6778.204)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.29.0', revision: '5fc1ec94cb'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [e6ec512e6488a6d209722b867475bc9a, findElement {value=Practice Questions, using=link text}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.204, chrome: {chromedriverVersion: 131.0.6778.264 (2d05e315153..., userDataDir: C:\Users\mahaj\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:58697}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:58697/devtoo..., se:cdpVersion: 131.0.6778.204, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: e6ec512e6488a6d209722b867475bc9a
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy21.isDisplayed(Unknown Source)
at dsAlgo_PageFactory.LinkedList_PageFactory.practiceQuestionsLinkDisplayed(LinkedList_PageFactory.java:141)
at dsAlgo_TestClasses.LinkedList_TestClass.practiceQuestionsNavigation(LinkedList_TestClass.java:265)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- practiceQuestionsNavigation -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="practiceQuestionsNavigation" time="13.320">
    <skipped/>
  </testcase> <!-- practiceQuestionsNavigation -->
  <testcase classname="dsAlgo_TestClasses.LinkedList_TestClass" name="practiceQuestionsNavigation" time="12.571">
    <skipped/>
  </testcase> <!-- practiceQuestionsNavigation -->
</testsuite> <!-- dsAlgo_TestClasses.LinkedList_TestClass -->
